In [1]:
import numpy as np

In [19]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [20]:
array_list = np.array(object = list_)

In [21]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.


Yes, there is a difference in the data types of the list_ and array_list variables. list_ is a standard Python list containing strings, while array_list is a NumPy array. NumPy arrays have a specific data type, which can be different from Python's standard list.

# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [22]:
print("data type of variables list_ ", type(list_))

data type of variables list_  <class 'list'>


In [23]:
print( "data type of array list_ ", type(array_list))

data type of array list_  <class 'numpy.ndarray'>


# Q3. Considering the following changes in the variable, array_list: 
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? 
# If so then print the data types of each and every element present in both the variables, list_ and arra_list.m

In [15]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [17]:
array_list = np.array(object = list_ , dtype = int)

In [18]:
array_list

array([1, 2, 3, 4, 5])

In [24]:
list_

['1', '2', '3', '4', '5']

Yes, there will be a difference in the data type of the elements present in list_ and array_list after specifying the dtype as int when creating the NumPy array. The elements in list_ are originally strings, but in array_list, they will be converted to integers due to the specified data type.

In [25]:
print('data type of list' , type(list_))
print('data type of array list', type(array_list))

data type of list <class 'list'>
data type of array list <class 'numpy.ndarray'>


# Consider the below code to answer further questions:
# import numpy as np
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
# num_array = np.array(object = num_list)
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [26]:
import numpy as np

In [27]:
num_list = [[1,2,3], [4,5,6]]

In [28]:
num_array = np.array(object = num_list)

In [29]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.shape(num_array)

(2, 3)

In [31]:
np.size(num_array)

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
## [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [35]:
array = np.zeros((3,3))

In [36]:
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q6. Create an identity matrix of shape (5,5) using numpy functions?
## [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [42]:
array1 = np.eye(5,5)

In [43]:
array1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])